sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: U5/IQyVPGzlTAs8hmcL91zsJHFvp57r2ZDsqPeZ8VZPC+GYg6N8Q2OCy5b3a+NQpw7h63fOLXEEvRL3NOcPGO/wgD0iSOLvLB8EzKRm1iCV3fLwnd/46Mekr631Y2c86nplf38xbiNPnchPYGIEctBHup+j1CjNL7neIrMWCWX3b7NGG9tnGwrAaEfuw0vPdfXSFJgRX41WQhn0KFr/3oq16kUmcdgHHRp4mfcdjdY7geotn1REjGxS9hhKLL8t29JYJbC4FlKuKV9WPOH0rFHtnY/U+r5UJofPQd793AF5CSgVR2ynqQZKRVnjz19hOUR7LAv4Vs/NVLhaP1vXPS5w5Ip+CpdFYSRKfS5+QgNsX1NN+JSPDlvYtui2NQprmqWRbJO9LhGiV3BO+1voAaYoiDDEZU4P/Hj1f7SHcsAZXz+RbJO9jp40hDbfdCUxmbSIkEQFQhFEaQmL7WO0b9oPPmHH0rupYFqTHZYtskurxq7c3diTDO/TRAO2QDllQTrJZrq4OUadoxtT2a/rprhk+mDTOzm8Ns75leqyOLlKa0frB45ISE8S6wnCq5bhmCaHeuU8jkG0VrcmumEGwUhtCJurArscIx+lUNkiBPu0iG14ZYP3Ek30lgMOSyVo6KKQg4rwCQinBNSZKrRo+rVcrIqKu0tSF5ZMPL/VVOoA=
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth acitivate-service-account --key-file service-account.json
  - gcloud config set project dailycodingproblems
  - gcloud config set compute/zone us-centra1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - echo No tests currently
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
